#!/usr/bin/env python

__version__ = "0.0.1"

import os
import sys

from config import config
from database import DB 

usage = '''
   usage: 

     task top (shows top of stack)

     task pop (removes top of stack)

     task add <task1> <task2> <task3> ... (adds tasks one by one) 

       <task> is a single word describing the task.
       Quote your input to express a multiple-word sequence
 
'''

def usage(msg=usage, exits=True):
  ''' set 'exits' to False if you don't want to exit the program ''' 

  sys.stdout.write(msg)
  if exits:
    sys.exit()



def main(db):
 
  if len(sys.argv) == 1:

    db.show_all_tasks()

  if len(sys.argv) == 2:
    
    action = sys.argv[1]

    if action in ('-h','--help'):
      usage()

    if action == 'add':
      usage() 

    if action == 'top':
      db.top()

    if action == 'pop':
      db.pop()

    if action == 'clear':
      db.clear()

  if len(sys.argv) > 2:
    
    action, tasks = sys.argv[1], sys.argv[2:]

    if action == 'add':
      db.add_tasks(db,tasks)

    else: 
      sys.stdout.write('unrecognized option %s' % action)


def init():

  _dir = config['data']['data_dir']
  _data_files = (config['data']['database_file'], config['data']['config_file'])
  
  if not os.path.exists(_dir):
    os.makedirs(_dir) 

  for f in _data_files:
    if not os.path.exists(f):
      open(f,'w').close() 

  
if __name__ == '__main__':
  init()
  db = DB(config['data']['database_file'])
  print db.db_file
  main(db)
