#!/usr/bin/env python

__version__ = "0.0.1"

import os
import sys

from config import config, usage
from database import DB 

def usage(msg=usage,exits=True):
  ''' set 'exits' to False if you don't want to exit the program ''' 

  sys.stdout.write(msg)

  if exits:
    sys.exit()

def main(db):
 
  if len(sys.argv) == 1:
    db.show_all_tasks()

  if len(sys.argv) == 2:
    action = sys.argv[1].strip()

    if action == '-h' or action == '--help':
      usage()

    if action == 'add':
      usage() 

    if action == 'top':
      db.top()

    if action == 'pop':
      db.pop()

    if action == 'clear':
      db.clear()

  if len(sys.argv) > 2:
    
    action, tasks = sys.argv[1], sys.argv[2:]

    if action == 'add':
      db.add_tasks(db,tasks)

    else: 
      sys.stdout.write('unrecognized option %s' % action)


def init():

  _dir = config['data']['data_dir']
  _data_files = (config['data']['database_file'], config['data']['config_file'])
  
  if not os.path.exists(_dir):
    os.makedirs(_dir) 

  for df in _data_files:
    if not os.path.exists(df):
      open(df,'w').close() 

if __name__ == '__main__':
  init()
  db = DB(config['data']['database_file'])
  main(db)
  print len(sys.argv)
